#!/usr/bin/env php
<?php

define('LARAVEL_START', microtime(true));

// Register the Composer Auto Loader
if (file_exists(__DIR__.'/vendor/autoload.php')) {
    require __DIR__.'/vendor/autoload.php';
} else {
    fwrite(STDERR, "Error: Ejecuta 'composer install' primero para instalar las dependencias de Laravel.\n");
    exit(1);
}

// Bootstrap Laravel and handle the command...
$app = require_once __DIR__.'/bootstrap/app.php';

$status = $app->handleCommand(new Symfony\Component\Console\Input\ArgvInput);

exit($status);
